//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubeSYSVN_Intern_anhthai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class anhthaiEntities : DbContext
    {
        public anhthaiEntities()
            : base("name=anhthaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SVR_BUMON> SVR_BUMON { get; set; }
        public virtual DbSet<SVR_COMPANY> SVR_COMPANY { get; set; }
        public virtual DbSet<SVR_STORE> SVR_STORE { get; set; }
        public virtual DbSet<SVR_USER> SVR_USER { get; set; }
        public virtual DbSet<SVR_VERSION> SVR_VERSION { get; set; }
        public virtual DbSet<SVR_VIEW> SVR_VIEW { get; set; }
    }
}
