//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubeSYSVN_Intern_anhthai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SVR_USER
    {
        [DisplayName("User Name")]
        [Required(ErrorMessage = "This Field is Required")]
        public string USERNAME { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This Field is Required")]
        public string PASSWORD { get; set; }

        public Nullable<decimal> COMPANY_ID { get; set; }

        public Nullable<decimal> BUMON_ID { get; set; }

        public Nullable<System.DateTime> INSERT_DATE { get; set; }

        public string INSERT_USER { get; set; }

        public Nullable<System.DateTime> UPDATE_DATE { get; set; }

        public string UPDATE_USER { get; set; }

        public Nullable<decimal> DEL_FLAG { get; set; }

        public string LoginErrorMsg { get; set; }
    }
}
