//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubeSYSVN_Intern_anhthai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SVR_VIEW
    {
        public string IMEI { get; set; }
        public Nullable<decimal> BUMON_ID { get; set; }
        public string STORE_CD { get; set; }
        public Nullable<decimal> PRODUCT_ID { get; set; }
        public string VIEW_DATE { get; set; }
        public Nullable<decimal> GENDER { get; set; }
        public Nullable<decimal> AGE { get; set; }
        public Nullable<decimal> VIEWS { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public decimal LOG_ID { get; set; }
    
        public virtual SVR_BUMON SVR_BUMON { get; set; }
        public virtual SVR_STORE SVR_STORE { get; set; }

        public string BUMON_NAME { get; set; }
        public string STORE_NAME { get; set; }
    }
}
