//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CubeSYSVN_Intern_anhthai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SVR_VERSION
    {
        public Nullable<decimal> TYPE_SEND { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> FROM_DATE { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> TO_DATE { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> INSERT_DATE { get; set; }

        public string INSERT_USER { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }

        public string UPDATE_USER { get; set; }

        public Nullable<decimal> DEL_FLAG { get; set; }

        public Nullable<decimal> BUMON_ID { get; set; }

        public decimal VERSION_NO { get; set; }
    
        public virtual SVR_BUMON SVR_BUMON { get; set; }

        //public string BUMON_NAME { get; set; }
        public SelectList BumonSelectList { get; set; }
    }
}
